site_name: LittleZhang's Wiki
nav:
    - Home: 
      - index.md
    - About: 
      - 关于: about.md
      - 测试: test.md

copyright: Copyright &copy; 2017 - 2020 littlezhang

theme:
  name: material
  language: zh
  palette:
    scheme: preference
    primary: indigo
  features:
    - instant
    - tabs

plugins:
  - search:
      lang: ja
